name = "hookfabrikken"
main = "src/index.js"
compatibility_date = "2026-08-24"

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "BRUK"
id = "d58db6f2dc704e73a2b058d5b2922b1b"
